services:
  # Backend API service
  - type: web
    name: safetyc-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # You'll set this in the Render dashboard
      - key: ALLOWED_ORIGINS
        fromService:
          name: safetyc-web
          type: web
          property: url
      - key: PORT
        value: 10000
    autoDeploy: true
    
  # Frontend web service
  - type: web
    name: safetyc-web
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: safetyc-api
          type: web
          property: url
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html